PETSearch/PETSearch/Models/Animals.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PETSearch.Models
{
    public class Animals
    {
        // hello world
        // maria here
        [Key] public int Animal_Id { get; set; }
        public string Race { get; set; }
        public string Color { get; set; }
        public string Gender { get; set; }
        public string Height { get; set; }
        public string Species { get; set; }

        [ForeignKey("LocationsFKanimals")]
        public string? Location { get; set; }
        public Locations? Locations { get; set; }

        [ForeignKey("ClinicsFKanimals")]
        public int? Clinic_Id { get; set; }
        public Clinics? Clinics { get; set; }

    }
}

PETSearch/PETSearch/Models/Clinics.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PETSearch.Models
{
    public class Clinics
    {
        [Key] public int Clinic_Id { get; set; }
        public string Clinic_Name { get; set; }

        [ForeignKey("LocationsFKclinics")]
        public string? Location { get; set; }
        public Locations? Locations { get; set; }

    }
}

PETSearch/PETSearch/Models/ErrorViewModel.cs
namespace PETSearch.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PETSearch/PETSearch/Models/Locations.cs
using System.ComponentModel.DataAnnotations;

namespace PETSearch.Models
{
    public class Locations
    {
        [Key] public int Location_Id { get; set; }
         public string Location { get; set; }
       

    }
}

PETSearch/PETSearch/Models/Person.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PETSearch.Models
{
    public class Person
    {
        [Key] public int Person_Id { get; set; }
        public string Person_Name { get; set; }
        public string Person_Email { get; set;}

        [ForeignKey("Locations")]
        public  string? Location { get; set;}
        public Locations? Locations { get; set; }
        public string Person_Username { get; set; }
        public string Person_Password { get; set; }

        [ForeignKey("Animals")]
        public int? Animal_Id { get; set; }
        public Animals? Animals { get; set; }

        public string Person_Phone_Number { get; set; }

    }
}

PETSearch/PETSearch/Models/Persons.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PETSearch.Models
{
    public class Persons
    {
        [Key] public int Person_Id { get; set; }
        public string Person_Name { get; set; }
        public string Person_Email { get; set;}

        [ForeignKey("LocationFKpersons")]
        public  string? Location { get; set;}
        public Locations? Locations { get; set; }
        public string Person_Username { get; set; }
        public string Person_Password { get; set; }

        [ForeignKey("AnimalsFKpersons")]
        public int? Animal_Id { get; set; }
        public Animals? Animals { get; set; }

        public string Person_Phone_Number { get; set; }

    }
}

PETSearch/PETSearch/Models/Vet.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PETSearch.Models
{
    public class Vet
    {
        //HELLO WORLDF
        [Key] public int Vet_Id { get; set; }

        public string Vet_Name { get; set; }

        public string Vet_Email { get; set; }

        public string Vet_Phone_Number { get; set; }

        [ForeignKey("Clinics")]

        public int? Clinic_Id { get; set; }

        public Clinics? Clinics { get; set; }


        public string Vet_Username { get; set; }

        public string Vet_Password { get; set; }    


    }
}

PETSearch/PETSearch/Models/Vets.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PETSearch.Models
{
    public class Vets
    {
        //HELLO WORLDF
        [Key] public int Vet_Id { get; set; }

        public string Vet_Name { get; set; }

        public string Vet_Email { get; set; }

        public string Vet_Phone_Number { get; set; }

        [ForeignKey("ClinicsFKvet")]

        public int? Clinic_Id { get; set; }

        public Clinics? Clinics { get; set; }


        public string Vet_Username { get; set; }

        public string Vet_Password { get; set; }    


    }
}

PETSearch/PETSearch/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using PETSearch.Models;
using System.Diagnostics;

namespace PETSearch.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PETSearch/PETSearch/Controllers/PersonsController.cs
using Microsoft.AspNetCore.Mvc;

namespace PETSearch.Controllers
{
    public class PersonsController : Controller
    {
        public IActionResult Login()
        {
            return View();
        }

        public IActionResult Register()
        {
            return View();
        }

    }
}

PETSearch/PETSearch/Controllers/VetsController.cs
using Microsoft.AspNetCore.Mvc;

namespace PETSearch.Controllers
{
    public class VetsController : Controller
    {
        public IActionResult Login()
        {
            return View();
        }

        public IActionResult Register()
        {
            return View();
        }
    }
}

PETSearch/PETSearch/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@*<h1>Hello</h1>*@


<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>Jumbotron Template for Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/jumbotron/">

    <!-- Bootstrap core CSS -->
    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="jumbotron.css" rel="stylesheet">
</head>

<body>

    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="#">PetSearch</a>
    </nav>

    <main role="main">

        <!-- Main jumbotron for a primary marketing message or call to action -->
        @*<div class="jumbotron">
            <div class="container">
                <h1 class="display-3">Hello, world!</h1>
                <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
                <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p>
            </div>
        </div>*@

        @*<input type="radio" name="gender" value="login"> Person  
        <input type="radio" name="gender" value="login"> Vet*@

        <div class="btn-group">
            <input type="radio" class="btn-check" name="options" id="option1" autocomplete="off" checked />
            <label class="btn btn-secondary" for="option1">Person</label>

            <li class="nav-item">
                <a asp-area="" asp-controller="Persons" asp-action="Register">Sign up</a>
                <span>&nbsp;or&nbsp;</span>
                <a asp-area="" asp-controller="Persons" asp-action="Login">Sign in</a>
            </li>

            @*<input type="radio" class="btn-check" name="options" id="option2" autocomplete="off" />
            <label class="btn btn-secondary" for="option2">Vet</label>*@

        </div>

        <div class="btn-group">
            @*<input type="radio" class="btn-check" name="options" id="option1" autocomplete="off" checked />
            <label class="btn btn-secondary" for="option1">Person</label>*@

            <input type="radio" class="btn-check" name="options" id="option2" autocomplete="off" />
            <label class="btn btn-secondary" for="option2">Vet</label>

            <li class="nav-item">
                <a asp-area="" asp-controller="Vets" asp-action="Register">Sign up</a>
                <span>&nbsp;or&nbsp;</span>
                <a asp-area="" asp-controller="Vets" asp-action="Login">Sign in</a>
            </li>

        </div>

        @*<form>
            <input type="radio" name="pageSelection" value="page1"> Page 1
            <br>
            <input type="radio" name="pageSelection" value="page2"> Page 2
        </form>*@

        @*<script>
            const radioButtons = document.querySelectorAll('input[type=radio][name=gender]');

            radioButtons.forEach(radioButton => {
                radioButton.addEventListener('click', () => {
                    const page = radioButton.value;
                    const url = ${ page }.html;
                    window.location.href = url;
                });
            });
        </script>*@

        @*<li class="nav-item">
            <a asp-area="" asp-controller="Persons" asp-action="Register">Sign up</a>
            <span>&nbsp;or&nbsp;</span>
            <a asp-area="" asp-controller="Persons" asp-action="Login">Sign in</a>
        </li>*@


    </main>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="../../assets/js/vendor/popper.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
</body>
</html>

PETSearch/PETSearch/Views/Persons/Login.cshtml
@model Persons

@{
    ViewData["Title"] = "Login";
}
<div class="row">
    <div class="col-md-6 offset-3">
        <p>
            <h4>Log in to your account</h4>
        </p>
        @if (TempData["Error"] != null)
        {
            <div class="col-md-12 alert alert-danger">
                <span><b>Sorry!</b> - @TempData["Error"]</span>
            </div>
        }
        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Login">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Person_Username" class="control-label"></label>
                        <input asp-for="Person_Username" class="form-control">
                        <span asp-validation-for="Person_Username" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Person_Password" class="control-label"></label>
                        <input asp-for="Person_Password" class="form-control" />
                        <span asp-validation-for="Person_Password" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input class="btn btn-outline-success float right" type="submit" value="Log in" />
                        <a class="btn btn-outline-secondary" asp-controller="Persons" asp-action="Login">Cancel</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

PETSearch/PETSearch/Views/Persons/Register.cshtml
@model Persons

@{
    ViewData["Title"] = "Sign up";
}

<div class="row">
    <div class="col-md-6 offset-3">
        <p>
            <h4>Sign up for a new account</h4>
        </p>

        @if (TempData["Error"] != null)
        {
            <div class="col-md-12 alert alert-danger">
                <span><b>Sorry!</b> - @TempData["Error"] </span>
            </div>
        }

        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Register">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="form-group">
                        <label asp-for="Person_Name" class="control-label"></label>
                        <input asp-for="Person_Name" class="form-control" />
                        <span asp-validation-for="Person_Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Person_Email" class="control-label"></label>
                        <input asp-for="Person_Email" class="form-control" />
                        <span asp-validation-for="Person_Email" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Person_Username" class="control-label"></label>
                        <input asp-for="Person_Username" class="form-control" />
                        <span asp-validation-for="Person_Username" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Person_Password" class="control-label"></label>
                        <input asp-for="Person_Password" class="form-control" />
                        <span asp-validation-for="Person_Password" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Person_Phone_Number" class="control-label"></label>
                        <input asp-for="Person_Phone_Number" class="form-control" />
                        <span asp-validation-for="Person_Phone_Number" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <input class="btn btn-outline-success float-right" type="submit" value="Sign up" />
                        <a class="btn btn-outline-secondary" asp-controller="Persons" asp-action="Register">Cancel</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

PETSearch/PETSearch/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PETSearch</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PETSearch.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PETSearch</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - PETSearch - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

PETSearch/PETSearch/Views/Vets/Login.cshtml
@model Vets

@{
    ViewData["Title"] = "Login";
}
<div class="row">
    <div class="col-md-6 offset-3">
        <p>
            <h4>Log in to your account</h4>
        </p>
        @if (TempData["Error"] != null)
        {
            <div class="col-md-12 alert alert-danger">
                <span><b>Sorry!</b> - @TempData["Error"]</span>
            </div>
        }
        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Login">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Vet_Username" class="control-label"></label>
                        <input asp-for="Vet_Username" class="form-control">
                        <span asp-validation-for="Vet_Username" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Vet_Password" class="control-label"></label>
                        <input asp-for="Vet_Password" class="form-control" />
                        <span asp-validation-for="Vet_Password" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input class="btn btn-outline-success float right" type="submit" value="Log in" />
                        <a class="btn btn-outline-secondary" asp-controller="Vets" asp-action="Login">Cancel</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

PETSearch/PETSearch/Views/Vets/Register.cshtml
@model Vets

@{
    ViewData["Title"] = "Sign up";
}

<div class="row">
    <div class="col-md-6 offset-3">
        <p>
            <h4>Sign up for a new account</h4>
        </p>

        @if (TempData["Error"] != null)
        {
            <div class="col-md-12 alert alert-danger">
                <span><b>Sorry!</b> - @TempData["Error"] </span>
            </div>
        }

        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Register">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="form-group">
                        <label asp-for="Vet_Name" class="control-label"></label>
                        <input asp-for="Vet_Name" class="form-control" />
                        <span asp-validation-for="Vet_Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Vet_Email" class="control-label"></label>
                        <input asp-for="Vet_Email" class="form-control" />
                        <span asp-validation-for="Vet_Email" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Vet_Username" class="control-label"></label>
                        <input asp-for="Vet_Username" class="form-control" />
                        <span asp-validation-for="Vet_Username" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Vet_Password" class="control-label"></label>
                        <input asp-for="Vet_Password" class="form-control" />
                        <span asp-validation-for="Vet_Password" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Vet_Phone_Number" class="control-label"></label>
                        <input asp-for="Vet_Phone_Number" class="form-control" />
                        <span asp-validation-for="Vet_Phone_Number" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Clinics" class="control-label"></label>
                        <input asp-for="Clinics" class="form-control" />
                        <span asp-validation-for="Clinics" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Clinic_Id" class="control-label"></label>
                        <input asp-for="Clinic_Id" class="form-control" />
                        <span asp-validation-for="Clinic_Id" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <input class="btn btn-outline-success float-right" type="submit" value="Sign up" />
                        <a class="btn btn-outline-secondary" asp-controller="Vets" asp-action="Register">Cancel</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>